language: android

android:
  components:
    - build-tools-23.0.0
    - android-23
    - sys-img-x86-android-23
    - add-on
    - extra

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/